version: "3.8"

services:
  ox-universe-fastapi:
    platform: linux/amd64
    image: 849441246713.dkr.ecr.ap-northeast-2.amazonaws.com/ox-universe-app:latest
    build:
      context: .
      dockerfile: Dockerfile.fastapi
      no_cache: true
      args:
        PROJECT_NAME: ox-universe
    environment:
      - ENVIRONMENT=production
      - PROJECT_NAME=ox-universe
      - PORT=8000
      - HOST=0.0.0.0
    ports:
      - "8000:8000"
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge