FROM public.ecr.aws/lambda/python:3.12

WORKDIR ${LAMBDA_TASK_ROOT}

ENV TZ=Asia/Seoul

# Install Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip \
    && pip install -r requirements.txt \
    && pip install yfinance --upgrade --no-cache-dir

# Copy application code
COPY . .

# Set Lambda handler
CMD ["myapi.main.handler"]
